---
title: MSHS Worked FTE Dashboard
author: Health System Operations
date: 'Publish Date: `r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

<style type="text/css">
div.main-container {
  max-width: 1760px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r, echo=F,warning=F,message=F,results='hide'}
source("Dashboard_Functions.R")
```

#### Reporting Period: `r rep`
#### * Department does not currently have a Premier productivity report
#### 1 FTE = 75 Worked Hours/Pay Period

```{r, echo=F,warning=F,message=F, results=F}
library(htmltools)
sites_services_df <- data %>% 
  ungroup() %>% 
  select(PAYROLL, CORPORATE.SERVICE.LINE) %>% 
  filter(!is.na(PAYROLL)) %>% 
  distinct()
system_service_lines <- 
  service_lines[which(!service_lines %in% c("IT", "HR", "CMO"))]
  
render_list <- list(h2("Mount Sinai Health System"),
                    sapply(X = system_service_lines,
                           function(x) {
                             list(h3(x),
                                  graph_data(serv.line = x),
                                  HTML(k(service = x)))},
                           simplify = FALSE,
                           USE.NAMES = TRUE),
                    sapply(X = site_list, function(y) {
                      site_service_lines <- sites_services_df %>%
                        filter(PAYROLL == y)
                      list(h2(y),
                           sapply(X = unique(
                             site_service_lines$CORPORATE.SERVICE.LINE),
                                  function(z) {
                                    list(h3(z),
                                         graph_data(hosp = y, serv.line = z),
                                         HTML(k(hosp = y, service = z)))
                                  },
                                  simplify = TRUE,
                                  USE.NAMES = TRUE
                                  )
                           )
                    },
                    simplify = TRUE,
                    USE.NAMES = TRUE))
```

```{r, echo=F,warning=F,message=F,fig.width=12, results='asis'}
tagList(render_list)
```